[package]
name = "emu-core-audio-driver"
version = "0.1.0"
authors = ["ferris <jake@fusetools.com>"]

[dependencies.emu-audio-types]
path = "../emu-audio-types"

[dependencies]
coreaudio-sys = "*"
libc = "*"